In [1]:
# Import NumPy
import numpy as np

# 1. Array Creation
a = np.array([1, 2, 3])           # Create 1D array
b = np.array([[1, 2], [3, 4]])    # Create 2D array
z = np.zeros((2, 3))              # Array of zeros
o = np.ones((3, 3))               # Array of ones
r = np.arange(0, 10, 2)           # Even numbers 0–8
l = np.linspace(0, 1, 5)          # 5 values between 0–1

In [2]:
# 2. Array Attributes
print(a.shape)     # Shape (rows, columns)
print(a.ndim)      # Number of dimensions
print(a.dtype)     # Data type of elements

(3,)
1
int64


In [3]:
# 3️⃣ Indexing & Slicing
print(b[0, 1])     # Access element (row 0, col 1)
print(r[1:4])      # Slice from index 1 to 3

2
[2 4 6]


In [4]:
# 4️⃣ Mathematical Operations
print(a + 5)       # Add scalar
print(a * 2)       # Multiply each element by 2
print(a + b[0])    # Element-wise addition (broadcasting)
print(np.dot(b, b))# Matrix multiplication

[6 7 8]
[2 4 6]


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [6]:
# 5️⃣ Useful Functions
print(np.sum(a))   # Sum of all elements
print(np.mean(a))  # Average
print(np.max(a))   # Maximum value
print(np.sqrt(a))  # Square root of each element

6
2.0
3
[1.         1.41421356 1.73205081]


In [7]:
# 6️⃣ Reshaping Arrays
x = np.arange(6).reshape(2, 3)    # Convert 1D to 2x3 array
print(x.T)                        # Transpose rows and columns

[[0 3]
 [1 4]
 [2 5]]


In [8]:
# 7️⃣ Random Numbers
rand_arr = np.random.rand(2, 3)   # Random floats (0 to 1)
rand_int = np.random.randint(1, 10, 5)  # 5 random ints between 1–9

In [9]:
# 8️⃣ Save and Load Arrays( no need)
np.save('array_file.npy', a)      # Save array
loaded = np.load('array_file.npy')# Load array

In [10]:
# 9️⃣ Linear Algebra
m = np.array([[1, 2], [3, 4]])
print(np.linalg.inv(m))           # Inverse
print(np.linalg.det(m))           # Determinant

[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004


In [11]:
# 🔟 Logical & Sorting
arr = np.array([1, 3, 2, 3])
print(np.unique(arr))             # Unique elements
print(np.sort(arr))               # Sorted array
print(np.where(arr > 2))          # Indices where condition true

[1 2 3]
[1 2 3 3]
(array([1, 3]),)


In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6],
              [7, 8, 9]])

# 4️⃣ Mathematical Operations
print(a + 5)        # Add scalar
print(a * 2)        # Multiply each element by 2
print(a + b[0])     # Element-wise addition
print(np.dot(b, b)) # Matrix multiplication


[6 7 8]
[2 4 6]
[5 7 9]


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)